---
victorialogs_vars:
  kubernetes:
    helm:
      chart:
        alias: vls
        name: victoria-logs-single
        version: v0.8.10
      repository:
        name: helm-charts
        org: VictoriaMetrics
        url: https://victoriametrics.github.io
    namespace: kube-system
    server:
      ingress:
        enabled: true
        subdomain: logs
      log_level: WARN
      resources:
        limits:
          cpu: null
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
      storage:
        enabled: true
        access_modes:
          - ReadWriteOnce
        class: longhorn
        size: 5Gi
      replicas: 1
      retention_period: 7d
    vector:
      enabled: true
      autoscaling:
        # -- If `false`, `replicas` value is set from `min_replicas` value
        enabled: true
        min_replicas: 1
        max_replicas: 3
        target:
          utilization_percentage:
            cpu: null
            memory: 80
      log_level: warn
      resources:
        limits:
          cpu: null
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 256Mi
