---
- name: Playbook Validation
  hosts: localhost
  become: false
  gather_facts: false
  tags: always
  tasks:
    - name: Validate tags
      ansible.builtin.fail:
        msg: |
          Improper usage of '--tags' flag:
          {% set invalid_tags = ansible_run_tags | difference(global_map.tags.play) %}
          {% if invalid_tags | length > 0 %}
            - invalid tag{% if invalid_tags | length > 1 %}s{% endif %}: {{ invalid_tags | join(', ') }}
          {% endif %}
            - valid tags: {{ global_map.tags.play | join(', ') }}
      when:
        - ansible_run_tags not in [(), ('all',)]
        - ansible_run_tags | difference(global_map.tags.play) | length > 0

    - name: Validate version
      ansible.builtin.fail:
        msg: Invalid Ansible version, minimum requirement is '{{ global_map.ansible.version }}'.
      when: ansible_version.full is not version(global_map.ansible.version, '>=')

- name: Cluster Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - cluster
  tags: cluster

- name: LoadBalancer Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  tags:
    - cluster
    - kubernetes
  tasks:
    - name: Setup loadbalancer
      ansible.builtin.import_role:
        name: k3s
        tasks_from: loadbalancer

- name: Kubernetes Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - helm
    - k3s
  serial:
    - 1
    - 2
    - 5
  tags: kubernetes

- name: Charts Provisioning
  hosts: server
  become: true
  gather_facts: true
  post_tasks:
    - name: Perform post-install tasks
      ansible.builtin.include_role:
        name: '{{ postinstall }}'
        tasks_from: postinstall
      loop:
        - argo-cd
        - cert-manager
        - cilium
        - coredns
        - external-dns
        - kured
        - longhorn
        - metrics-server
        - victoria-logs
      loop_control:
        loop_var: postinstall
  roles:
    - cilium
    - coredns
    - cert-manager
    - external-dns
    - argo-cd
    - kured
    - longhorn
    - metrics-server
    - victoria-logs
    - victoria-metrics
  tags: charts
