---
- name: Cluster Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - role: cluster
  tags: cluster

- name: LoadBalancer Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  tags:
    - cluster
    - kubernetes
  tasks:
    - name: Setup loadbalancer
      ansible.builtin.import_role:
        name: k3s
        tasks_from: loadbalancer

- name: Kubernetes Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  post_tasks:
    - name: Perform post-install tasks
      ansible.builtin.import_role:
        name: k3s
        tasks_from: postinstall
  roles:
    - role: helm
    - role: k3s
  serial:
    - 1
    - 2
    - 5
  tags: kubernetes

- name: Charts Provisioning
  hosts: server
  become: true
  gather_facts: true
  post_tasks:
    - name: Perform post-install tasks
      ansible.builtin.import_role:
        name: cilium
        tasks_from: postinstall
  roles:
    - role: cilium
    - role: certmanager
    - role: cloudflare
    - role: longhorn
    - role: prometheus
    - role: kured
    - role: argocd
  tags: charts
