---
- name: Cluster Reset
  hosts: cluster
  become: true
  gather_facts: true
  serial:
    - 3
    - 5
  post_tasks:
    - name: Remove archived journal files
      ansible.builtin.command:
        cmd: journalctl --rotate --vacuum-time=1s
      changed_when: false
  tasks:
    - name: Get packages information
      ansible.builtin.package_facts:
      tags: always

    - name: Reset cluster
      ansible.builtin.include_role:
        name: '{{ reset }}'
        tasks_from: reset
      loop:
        - cluster
        - k3s
        - argo-cd
        - cert-manager
        - cilium
        - coredns
        - external-dns
        - kured
        - longhorn
        - metrics-server
        - victoria-logs
        - victoria-metrics
        - helm
      loop_control:
        loop_var: reset
  vars_prompt:
    - name: prompt_remove_packages
      prompt: Remove installed apt packages? [Y/n]
      default: 'n'
      private: false
