---
- name: Cluster Reset
  hosts: cluster
  become: true
  gather_facts: true
  serial:
    - 3
    - 4
  post_tasks:
    - name: Remove archived journal files
      ansible.builtin.command:
        cmd: journalctl --rotate --vacuum-time=1s
      changed_when: false
  tasks:
    - name: Get packages information
      ansible.builtin.package_facts:
      tags: always

    - name: Reset cluster
      ansible.builtin.include_role:
        apply:
          tags: '{{ reset }}'
        name: '{{ reset }}'
        tasks_from: reset
      loop:
        - cluster
        - k3s
        - argo-cd
        - cert-manager
        - cilium
        - coredns
        - external-dns
        - kured
        - longhorn
        - metrics-server
        - victoria-logs
        - victoria-metrics
        - helm
      loop_control:
        loop_var: reset
      tags: always
      when: (ansible_run_tags == ['all']) or (reset in ansible_run_tags)
  vars_prompt:
    - name: prompt_remove_packages
      prompt: Remove installed apt packages? [Y/n]
      default: 'n'
      private: false
