---
- name: Cluster Reset
  hosts: cluster
  become: true
  gather_facts: true
  serial:
    - 3
    - 5
  post_tasks:
    - name: Remove archived journal files
      ansible.builtin.command:
        cmd: journalctl --rotate --vacuum-time=1s
      changed_when: true
  tasks:
    - name: Get packages information
      ansible.builtin.package_facts:
      tags: always

    - name: Reset cluster
      ansible.builtin.include_role:
        apply:
          tags: '{{ role }}'
        name: '{{ role }}'
        tasks_from: reset
      loop:
        - cluster
        - k3s
        - argocd
        - certmanager
        - cilium
        - cloudflare
        - kured
        - longhorn
        - victorialogs
        - victoriametrics
        - helm
      loop_control:
        loop_var: role
      tags: always
      when: (role in ansible_run_tags) or (ansible_run_tags == ['all'])
  vars_prompt:
    - name: prompt_remove_packages
      prompt: Remove installed apt packages? [Y/n]
      default: 'n'
      private: false
