---
- name: Tags Validation
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Validate tags
      ansible.builtin.fail:
        msg: |
          Improper usage of '--tags' flag:
          {% set invalid_tags = ansible_run_tags | difference(global_map.tags.role) %}
          {% if invalid_tags | length > 0 %}
            - invalid tag{% if invalid_tags | length > 1 %}s{% endif %}: {{ invalid_tags | join(', ') }}
          {% endif %}
            - valid tags: {{ global_map.tags.role | join(', ') }}
      tags: always
      when:
        - ansible_run_tags not in [[], ['all']]
        - ansible_run_tags | difference(global_map.tags.role) | length > 0

- name: Cluster Upgrade
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Role Upgrade
      ansible.builtin.include_role:
        apply:
          tags: '{{ upgrade }}'
        name: '{{ upgrade }}'
        tasks_from: upgrade
      loop: '{{ global_map.tags.role }}'
      loop_control:
        loop_var: upgrade
      tags: always
      when: (upgrade in ansible_run_tags)
