---
- name: Cluster Upgrade
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Roles Upgrade
      ansible.builtin.include_role:
        apply:
          tags: '{{ upgrade.role }}'
        name: '{{ upgrade.role }}'
        tasks_from: '{{ upgrade.tasks }}'
      loop:
        - {role: certmanager, tasks: main}
        - {role: cilium, tasks: main}
        - {role: cilium, tasks: postinstall}
        - {role: cloudflare, tasks: main}
<<<<<<< HEAD
        - {role: devtron, tasks: main}
=======
        - {role: cluster, tasks: upgrade}
>>>>>>> main
        - {role: helm, tasks: main}
        - {role: k3s, tasks: upgrade}
        - {role: kured, tasks: main}
        - {role: longhorn, tasks: main}
        - {role: prometheus, tasks: main}
      loop_control:
        loop_var: upgrade
      tags: always
      when: upgrade.role in ansible_run_tags
