---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - cert-manager
    - external-dns
    - k3s
    - victoria-metrics
    - cilium
  loop_control:
    loop_var: role

- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ cilium_project.url }}/{{ cilium_project.tag }}'
        timeout: 5
      run_once: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate cli release file url
      ansible.builtin.uri:
        url: '{{ cilium_project.release.cli.url }}/{{ cilium_project.release.cli.file }}'
        timeout: 5
      run_once: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate gateway-api release file url
      ansible.builtin.uri:
        url: '{{ cilium_project.release.gateway_api.url }}/{{ cilium_project.release.gateway_api.file }}'
        timeout: 5
      run_once: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate hubble release file url
      ansible.builtin.uri:
        url: '{{ cilium_project.release.hubble.url }}/{{ cilium_project.release.hubble.file }}'
        timeout: 5
      run_once: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Chart Validation
      block:
        - name: Add repository
          kubernetes.core.helm_repository:
            name: '{{ cilium_vars.kubernetes.helm.repository.org }}'
            repo_url: '{{ cilium_map.helm.repository.url }}'

        - name: Get deployed chart release info
          kubernetes.core.helm_info:
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ cilium_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ cilium_vars.kubernetes.namespace }}'
          register: release
          changed_when: false

        - name: Set comparison fact
          ansible.builtin.set_fact:
            comparison:
              chart: '{{ cilium_vars.kubernetes.helm.chart.version }}'
              release: "v{{ (release.status.chart | default('0')).split('-')[-1] }}"

        - name: Validate certificate values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'certificate.j2') }}"

        - name: Validate cluster issuer values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'cluster_issuer.j2') }}"

        - name: Validate gateway values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'gateway.j2') }}"

        - name: Validate insecure http route values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'http_route_insecure.j2') }}"

        - name: Validate secure http route values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'http_route_secure.j2') }}"

        - name: Validate l2 announcement policy values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'l2_announcement_policy.j2') }}"

        - name: Validate loadbalancer ip pool values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'loadbalancer_ip_pool.j2') }}"

        - name: Set chart setup fact
          ansible.builtin.set_fact:
            cilium_setup: true

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            cilium_postinstall: false

        - name: Validate setup chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Set chart values fact
          ansible.builtin.set_fact:
            chart_values: "{{ lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml }}"

        - name: Update chart setup fact
          ansible.builtin.set_fact:
            cilium_setup: false

        - name: Validate post-setup chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Update chart values fact
          ansible.builtin.set_fact:
            chart_values: "{{ chart_values | combine(lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml, recursive=true) }}"
          when:
            - comparison.release is version('0', '>')
            - comparison.release != comparison.chart

        - name: Update chart postinstall fact
          ansible.builtin.set_fact:
            cilium_postinstall: true

        - name: Validate postinstall chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Chart Deployment Simulation
          when:
            - comparison.release is version('0', '>')
            - comparison.release != comparison.chart
          block:
            - name: Update chart values fact
              ansible.builtin.set_fact:
                chart_values: "{{ chart_values | combine(lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml, recursive=true) }}"

            - name: Set chart values url fact
              ansible.builtin.set_fact:
                chart_values_url:
                  - '{{ cilium_map.helm.platform.raw }}'
                  - '{{ cilium_vars.kubernetes.helm.repository.org }}'
                  - '{{ cilium_vars.kubernetes.helm.repository.name }}/refs/tags/%s/install/kubernetes'
                  - '{{ cilium_vars.kubernetes.helm.chart.name }}/values.yaml'

            - name: Compare chart values
              ansible.builtin.command:
                cmd: bash -c "diff -u
                  <(curl -s {{ chart_values_url | join('/') | format(comparison.release) }})
                  <(curl -s {{ chart_values_url | join('/') | format(comparison.chart) }})"
              register: result
              delay: 1
              retries: 3
              until: result is not failed
              changed_when: false
              failed_when: result.rc > 1

            - name: Chart values comparison result
              ansible.builtin.debug:
                msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart comparison changes found.' }}"

            - name: Set chart deployment simulation command fact
              ansible.builtin.set_fact:
                simulation_command:
                  - 'helm diff upgrade {{ cilium_vars.kubernetes.helm.chart.name }} {{ cilium_map.helm.chart.reference }}'
                  - '  --kubeconfig {{ k3s_project.cluster.kubeconfig }} --namespace {{ cilium_vars.kubernetes.namespace }}'
                  - '  --version {{ cilium_vars.kubernetes.helm.chart.version }} --context 3 --values -'

            - name: Display chart deployment simulation command
              ansible.builtin.debug:
                msg: "{{ simulation_command | join(' \\\n') }} << 'EOF'\n{{ chart_values | to_nice_yaml(indent=2) }}EOF"

            - name: Run chart deployment simulation command
              ansible.builtin.command:
                cmd: "{{ simulation_command | join(' ') }}"
                stdin: "{{ chart_values | to_yaml }}"
              register: result
              delay: 1
              retries: 3
              until: result is not failed
              changed_when: false

            - name: Chart deployment simulation result
              ansible.builtin.debug:
                msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart deployment errors found.' }}"
