body:
  - type: dropdown
    id: topic
    attributes:
      label: Discussion Topic
      options:
        - 'Configuration'
        - 'New Idea'
        - 'Possible Bug'
        - 'Other'
      default: 1
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please tell us more about your question or problem.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please copy and paste any relevant log output.
        Tip: This will be automatically formatted into code, there is no need to insert backticks.
      render: shell
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else
      description: |
        Links? References? Anything that will provide more context.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this discussion, you agree to follow our [Code of Conduct](https://github.com/axivo/k3s-cluster/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow project's Code of Conduct
          required: true
