---
- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ metricsserver_vars.kubernetes.helm.repository.name }}'
        repo_url: '{{ metricsserver_map.helm.repository.url }}'
        force_update: true

    - name: Chart Setup
      run_once: true
      block:
        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            metricsserver_postinstall: false

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: '{{ metricsserver_map.helm.chart.reference }}'
            chart_version: '{{ metricsserver_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ metricsserver_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ metricsserver_vars.kubernetes.namespace }}'
            timeout: '{{ metricsserver_map.helm.timeout }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            create_namespace: true
            update_repo_cache: true
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed
