---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - cert-manager
    - external-dns
    - k3s
    - victoria-metrics
    - metrics-server
  loop_control:
    loop_var: role

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ metricsserver_vars.kubernetes.helm.repository.name }}'
        repo_url: '{{ metricsserver_map.helm.repository.url }}'
        force_update: true
      register: metricsserver_result
      delay: 1
      retries: 3
      until: metricsserver_result is not failed

    - name: Chart Setup
      run_once: true
      block:
        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            metricsserver_postinstall: false

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: '{{ metricsserver_map.helm.chart.reference }}'
            chart_version: '{{ metricsserver_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ metricsserver_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ metricsserver_vars.kubernetes.namespace }}'
            timeout: '{{ metricsserver_map.helm.timeout }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            create_namespace: true
            update_repo_cache: true
            wait: true
          register: metricsserver_result
          delay: 1
          retries: 3
          until: metricsserver_result is not failed
