---
- name: Role Post-Install
  when: inventory_hostname in k3s_map.server.hosts
  run_once: true
  block:
    - name: Metrics Setup
      when: longhorn_map.metrics.service.monitor.enabled is truthy
      block:
        - name: Update chart postinstall fact
          ansible.builtin.set_fact:
            longhorn_postinstall: true

        - name: Update chart postinstall values
          kubernetes.core.helm:
            chart_ref: '{{ longhorn_map.helm.chart.reference }}'
            chart_version: '{{ longhorn_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ longhorn_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ longhorn_vars.kubernetes.namespace }}'
            timeout: '{{ longhorn_map.helm.timeout }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            reset_values: false
            reuse_values: true
            wait: true
          register: longhorn_result
          delay: 1
          retries: 3
          until: longhorn_result is not failed
