---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - cert-manager
    - cluster
    - external-dns
    - k3s
    - victoria-metrics
  loop_control:
    loop_var: role

- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ victoriametrics_project.helm.chart.victoriametrics.url }}/{{ victoriametrics_project.helm.chart.victoriametrics.tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate project dependency url
      ansible.builtin.uri:
        url: '{{ victoriametrics_project.helm.chart.prometheus.url }}/{{ victoriametrics_project.helm.chart.prometheus.tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Chart Validation
      block:
        - name: Add repository
          kubernetes.core.helm_repository:
            name: '{{ item.org }}'
            repo_url: '{{ item.url }}/{{ item.name }}'
          loop: '{{ victoriametrics_map.helm.repository }}'

        - name: Get deployed chart info
          kubernetes.core.helm_info:
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias }}'
            namespace: '{{ victoriametrics_vars.kubernetes.namespace }}'
          register: release
          delay: 1
          retries: 3
          until: result is not failed
          changed_when: false

        - name: Set comparison fact
          ansible.builtin.set_fact:
            comparison:
              chart: '{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.version[1:] }}'
              release: "{{ (release.status.chart | default('0')).split('-')[-1] }}"

        - name: Set credentials fact
          ansible.builtin.set_fact:
            credentials: "{{ lookup('ansible.builtin.template', 'credentials.j2') | from_yaml }}"
          no_log: true

        - name: Set string data fact
          ansible.builtin.set_fact:
            string_data:
              admin_password: "{{ credentials.stringData['admin-password'] | b64encode }}"
              admin_user: "{{ credentials.stringData['admin-user'] | b64encode }}"
              smtp_password: "{{ credentials.stringData['smtp-password'] | b64encode }}"
              smtp_user: "{{ credentials.stringData['smtp-user'] | b64encode }}"
          no_log: true

        - name: Validate alertmanager configuration values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'config_alertmanager.j2') }}"

        - name: Validate credentials values
          ansible.builtin.debug:
            msg: >
              {{ credentials | combine({
                'stringData': {
                  'admin-password': string_data.admin_password,
                  'admin-user': string_data.admin_user,
                  'smtp-password': string_data.smtp_password,
                  'smtp-user': string_data.smtp_user
                }})
              }}

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Chart Deployment Simulation
          when:
            - comparison.release is version('0', '>')
            - comparison.release != comparison.chart
          block:
            - name: Set chart values url fact
              ansible.builtin.set_fact:
                chart_values_url:
                  - '{{ victoriametrics_map.helm.platform.raw }}'
                  - '{{ victoriametrics_vars.kubernetes.helm.repository.org }}'
                  - '{{ victoriametrics_vars.kubernetes.helm.repository.name }}/refs/tags'
                  - '{{ victoriametrics_vars.kubernetes.helm.chart.name }}-%s/charts'
                  - '{{ victoriametrics_vars.kubernetes.helm.chart.name }}/values.yaml'

            - name: Compare chart values
              ansible.builtin.command:
                cmd: bash -c "diff -u
                  <(curl -s {{ chart_values_url | join('/') | format(comparison.release) }})
                  <(curl -s {{ chart_values_url | join('/') | format(comparison.chart) }})"
              register: result
              delay: 1
              retries: 3
              until: result is not failed
              changed_when: false
              failed_when: result.rc > 1

            - name: Chart values comparison result
              ansible.builtin.debug:
                msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart comparison changes found.' }}"

            - name: Set release chart fact
              ansible.builtin.set_fact:
                release_chart:
                  - '{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias }}'
                  - '{{ victoriametrics_project.helm.chart.victoriametrics.reference }}'

            - name: Set chart deployment simulation command fact
              ansible.builtin.set_fact:
                simulation_command:
                  - "helm diff upgrade {{ release_chart | join(' ') }}"
                  - '  --kubeconfig {{ k3s_project.cluster.kubeconfig }} --namespace {{ victoriametrics_vars.kubernetes.namespace }}'
                  - '  --version {{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.version }} --context 3 --values -'

            - name: Display chart deployment simulation command
              ansible.builtin.debug:
                msg: "{{ simulation_command | join(' \\\n') }} << 'EOF'\n{{ lookup('ansible.builtin.template', 'values.j2') }}EOF"

            - name: Run chart deployment simulation command
              ansible.builtin.command:
                cmd: "{{ simulation_command | join(' ') }}"
                stdin: "{{ lookup('ansible.builtin.template', 'values.j2') }}"
              register: result
              delay: 1
              retries: 3
              until: result is not failed
              changed_when: false

            - name: Chart deployment simulation result
              ansible.builtin.debug:
                msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart deployment errors found.' }}"
