---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - cert-manager
    - cluster
    - coredns
    - external-dns
    - k3s
    - victoria-metrics
  loop_control:
    loop_var: role

- name: Role Validation
  when: (ansible_run_tags in [(), ('all',)]) or ('victoria-metrics' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ victoriametrics_project.helm.chart.victoriametrics.url }}/{{ victoriametrics_project.helm.chart.victoriametrics.tag }}'
        timeout: 5
      register: victoriametrics_result
      delay: 1
      retries: 3
      until: victoriametrics_result is not failed

    - name: Validate project dependency url
      ansible.builtin.uri:
        url: '{{ victoriametrics_project.helm.chart.prometheus.url }}/{{ victoriametrics_project.helm.chart.prometheus.tag }}'
        timeout: 5
      register: victoriametrics_result
      delay: 1
      retries: 3
      until: victoriametrics_result is not failed

    - name: Chart Validation
      block:
        - name: Update repository
          kubernetes.core.helm_repository:
            name: '{{ item.org }}'
            repo_url: '{{ item.url }}/{{ item.name }}'
            force_update: true
          loop: '{{ victoriametrics_map.helm.repository }}'

        - name: Validate cluster kubeconfig path
          ansible.builtin.stat:
            path: '{{ k3s_project.cluster.kubeconfig }}'
          register: victoriametrics_kubeconfig
          changed_when: false

        - name: Get deployed chart release info
          kubernetes.core.helm_info:
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias }}'
            namespace: '{{ victoriametrics_vars.kubernetes.namespace }}'
          register: victoriametrics_release
          when: victoriametrics_kubeconfig.stat.exists
          changed_when: false

        - name: Set comparison fact
          ansible.builtin.set_fact:
            victoriametrics_comparison:
              chart: "{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.version[1:] }}"
              release: "{{ victoriametrics_release.status.chart | default('0') | replace('k8s', '') | regex_search('[0-9.]+') }}"

        - name: Set credentials fact
          ansible.builtin.set_fact:
            victoriametrics_credentials: "{{ lookup('ansible.builtin.template', 'credentials.j2') | from_yaml }}"
          no_log: true

        - name: Set string data fact
          ansible.builtin.set_fact:
            victoriametrics_string_data:
              admin_password: "{{ victoriametrics_credentials.stringData['admin-password'] | b64encode }}"
              admin_user: "{{ victoriametrics_credentials.stringData['admin-user'] | b64encode }}"
              smtp_password: "{{ victoriametrics_credentials.stringData['smtp-password'] | b64encode }}"
              smtp_user: "{{ victoriametrics_credentials.stringData['smtp-user'] | b64encode }}"
          no_log: true

        - name: Validate alertmanager configuration values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'config_alertmanager.j2') | trim | regex_replace('\\n[\\s\\t]*\\n', '\\n') }}"

        - name: Validate alerting rules
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', item) }}"
          with_fileglob:
            - '{{ role_path }}/templates/alerts/*.j2'

        - name: Validate credentials values
          ansible.builtin.debug:
            msg: >
              {{ victoriametrics_credentials | combine({
                'stringData': {
                  'admin-password': victoriametrics_string_data.admin_password,
                  'admin-user': victoriametrics_string_data.admin_user,
                  'smtp-password': victoriametrics_string_data.smtp_password,
                  'smtp-user': victoriametrics_string_data.smtp_user
                }})
              }}

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Chart Deployment Simulation
          when:
            - victoriametrics_comparison.release is version('0', '>')
            - victoriametrics_comparison.release != victoriametrics_comparison.chart
          block:
            - name: Simulate chart deployment
              ansible.builtin.command:
                cmd: >-
                  helm diff upgrade
                    {{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias }}
                    {{ victoriametrics_project.helm.chart.victoriametrics.reference }}
                    --kubeconfig {{ k3s_project.cluster.kubeconfig }}
                    --namespace {{ victoriametrics_vars.kubernetes.namespace }}
                    --version {{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.version }}
                    --context 3 --values -
                stdin: "{{ lookup('ansible.builtin.template', 'values.j2') }}"
              register: victoriametrics_result
              delay: 1
              retries: 3
              until: victoriametrics_result is not failed
              changed_when: false

            - name: Chart deployment simulation result
              ansible.builtin.debug:
                msg: "{{ victoriametrics_result.stdout if victoriametrics_result.stdout | length > 0 else 'No chart deployment errors found.' }}"

            - name: Compare chart values
              ansible.builtin.command:
                cmd: bash -c "{{
                  ' '.join(['diff', '-u', '<(curl', '-s ' +
                    '/'.join([victoriametrics_map.helm.platform.raw,
                      victoriametrics_vars.kubernetes.helm.repository.victoriametrics.org,
                      victoriametrics_vars.kubernetes.helm.repository.victoriametrics.name, 'refs', 'tags',
                      '-'.join([victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name, victoriametrics_comparison.release]), 'charts',
                      victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name, 'values.yaml']) + ')',
                  '<(curl', '-s ' +
                    '/'.join([victoriametrics_map.helm.platform.raw,
                      victoriametrics_vars.kubernetes.helm.repository.victoriametrics.org,
                      victoriametrics_vars.kubernetes.helm.repository.victoriametrics.name, 'refs', 'tags',
                      '-'.join([victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name, victoriametrics_comparison.chart]), 'charts',
                      victoriametrics_vars.kubernetes.helm.chart.victoriametrics.name, 'values.yaml']) + ')'])
                  }}"
              register: victoriametrics_result
              delay: 1
              retries: 3
              until: victoriametrics_result is not failed
              changed_when: false
              failed_when: victoriametrics_result.rc > 1

            - name: Chart values comparison result
              ansible.builtin.debug:
                msg: "{{ victoriametrics_result.stdout if victoriametrics_result.stdout | length > 0 else 'No chart comparison changes found.' }}"
