name: Bug Report
description: Report an encountered bug.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > If you have usage questions, please read first the [Wiki](https://axivo.com/k3s-cluster) and
        > use [GitHub Discussions](https://github.com/axivo/k3s-cluster/discussions), for community support.
  - type: checkboxes
    attributes:
      label: Existing Issues
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened
      description: What did you expect to happen?
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: kernel-version
    attributes:
      label: Kernel Version
      description: |
        Which kernel version is the cluster running on? (run `uname -a`)
        > This will be automatically formatted into code, there is no need to insert backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: |
        Which Kubernetes version is the cluster running on? (run `kubectl version`)
        > This will be automatically formatted into code, there is no need to insert backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please copy and paste any relevant log output.
        > This will be automatically formatted into code, there is no need to insert backticks.
      render: shell
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else
      description: |
        Links? References? Anything that will provide more context about the issue you are encountering.
        > You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/axivo/k3s-cluster/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow project's Code of Conduct
          required: true
