---
- name: Import facts
  ansible.builtin.include_role:
    name: '{{ item }}'
    tasks_from: facts
  loop:
    - cloudflare
    - k3s

- name: Role Post-Install
  when: ansible_host in k3s_server_hosts
  run_once: true
  block:
    - name: Set chart postinstall fact
      ansible.builtin.set_fact:
        argocd_postinstall: true

    - name: Update chart postinstall values
      kubernetes.core.helm:
        chart_ref: '{{ argocd_project_chart }}'
        chart_version: '{{ argocd_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        name: '{{ argocd_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ argocd_vars.kubernetes.namespace }}'
        values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
        reset_values: false
        reuse_values: true
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed
