---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - external-dns
    - k3s
    - victoria-metrics
    - kured
  loop_control:
    loop_var: role

- name: Role Validation
  when: ('validation' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ kured_project.url }}/{{ kured_project.tag }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Chart Validation
      block:
        - name: Add repository
          kubernetes.core.helm_repository:
            name: '{{ kured_vars.kubernetes.helm.repository.org }}'
            repo_url: '{{ kured_map.helm.repository.url }}'

        - name: Get deployed chart release info
          kubernetes.core.helm_info:
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ kured_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ kured_vars.kubernetes.namespace }}'
          register: release
          changed_when: false

        - name: Set comparison fact
          ansible.builtin.set_fact:
            comparison:
              chart: '{{ kured_map.helm.chart.version }}'
              release: "{{ (release.status.chart | default('0')).split('-')[-1] }}"

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            kured_postinstall: false

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Set chart values fact
          ansible.builtin.set_fact:
            chart_values: "{{ lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml }}"
          when:
            - comparison.release is version('0', '>')
            - comparison.release != comparison.chart

        - name: Update chart postinstall fact
          ansible.builtin.set_fact:
            kured_postinstall: true

        - name: Validate postinstall chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Chart Deployment Simulation
          when:
            - comparison.release is version('0', '>')
            - comparison.release != comparison.chart
          block:
            - name: Update chart values fact
              ansible.builtin.set_fact:
                chart_values: "{{ chart_values | combine(lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml, recursive=true) }}"

            - name: Set chart values url fact
              ansible.builtin.set_fact:
                chart_values_url:
                  - '{{ kured_map.helm.platform.raw }}'
                  - '{{ kured_vars.kubernetes.helm.repository.org }}'
                  - '{{ kured_vars.kubernetes.helm.repository.name }}/refs/tags'
                  - '{{ kured_vars.kubernetes.helm.chart.name }}-%s/charts'
                  - '{{ kured_vars.kubernetes.helm.chart.name }}/values.yaml'

            - name: Compare chart values
              ansible.builtin.command:
                cmd: bash -c "diff -u
                  <(curl -s {{ chart_values_url | join('/') | format(comparison.release) }})
                  <(curl -s {{ chart_values_url | join('/') | format(comparison.chart) }})"
              register: result
              delay: 1
              retries: 3
              until: result is not failed
              changed_when: false
              failed_when: result.rc > 1

            - name: Chart values comparison result
              ansible.builtin.debug:
                msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart comparison changes found.' }}"

            - name: Set chart deployment simulation command fact
              ansible.builtin.set_fact:
                simulation_command:
                  - 'helm diff upgrade {{ kured_vars.kubernetes.helm.chart.name }} {{ kured_map.helm.chart.reference }}'
                  - '  --kubeconfig {{ k3s_project.cluster.kubeconfig }} --namespace {{ kured_vars.kubernetes.namespace }}'
                  - '  --version {{ kured_vars.kubernetes.helm.chart.version }} --context 3 --values -'

            - name: Display chart deployment simulation command
              ansible.builtin.debug:
                msg: "{{ simulation_command | join(' \\\n') }} << 'EOF'\n{{ chart_values | to_nice_yaml(indent=2) }}EOF"

            - name: Run chart deployment simulation command
              ansible.builtin.command:
                cmd: "{{ simulation_command | join(' ') }}"
                stdin: "{{ chart_values | to_yaml }}"
              register: result
              delay: 1
              retries: 3
              until: result is not failed
              changed_when: false

            - name: Chart deployment simulation result
              ansible.builtin.debug:
                msg: "{{ result.stdout if result.stdout | length > 0 else 'No chart deployment errors found.' }}"
