---
- name: Import facts
  ansible.builtin.include_role:
    name: '{{ item }}'
    tasks_from: facts
  loop:
    - cloudflare
    - k3s

- name: Role Validation
  run_once: true
  block:
    - name: Validate inventory
      ansible.builtin.assert:
        that: k3s_ha_cluster or k3s_non_ha_cluster
        fail_msg: |-
          ERROR: Invalid number of 'server' type nodes.
            - Defined nodes: {{ k3s_server_hosts | length }} ({{ k3s_server_hosts | join(', ') }})
            - Valid values: 1, higher than 2
          FIXES:
            - Update the number of 'server' type nodes, into inventory file.
        quiet: true

    - name: Validate release binary url
      ansible.builtin.uri:
        url: '{{ k3s_release_url_file }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Validate release checksum url
      ansible.builtin.uri:
        url: '{{ k3s_release_url_checksum }}'
        timeout: 5
      register: result
      delay: 1
      retries: 3
      until: result is not failed
