---
- name: Role Post-Install
  when:
    - inventory_hostname in k3s_map.server.hosts
    - coredns_map.metrics.service.monitor.enabled is truthy
  run_once: true
  block:
    - name: Update chart postinstall fact
      ansible.builtin.set_fact:
        coredns_postinstall: true

    - name: Update chart postinstall values
      kubernetes.core.helm:
        chart_ref: '{{ coredns_map.helm.chart.reference }}'
        chart_version: '{{ coredns_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
        name: '{{ coredns_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ coredns_vars.kubernetes.namespace }}'
        timeout: '{{ coredns_map.helm.timeout }}'
        values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
        reset_values: false
        reuse_values: true
        wait: true
      register: coredns_result
      delay: 1
      retries: 3
      until: coredns_result is not failed
