---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - external-dns
    - k3s
    - victoria-metrics
    - cert-manager
  loop_control:
    loop_var: role

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        timeout: 30
      any_errors_fatal: true

    - name: Set checksums fact
      ansible.builtin.uri:
        url: '{{ certmanager_project.release.url }}/{{ certmanager_project.release.checksum }}'
        return_content: true
      register: certmanager_checksums
      delay: 1
      retries: 3
      until: certmanager_checksums is not failed
      check_mode: false
      run_once: true

    - name: Set sha256 checksum fact
      ansible.builtin.set_fact:
        certmanager_sha256_checksum: "{{ item.split(' ')[0] }}"
      loop: "{{ certmanager_checksums.content.split('\n') }}"
      when: item is search(certmanager_vars.release.file + '$')
      run_once: true

    - name: Install binary
      ansible.builtin.get_url:
        url: '{{ certmanager_project.release.url }}/{{ certmanager_project.release.file }}'
        checksum: sha256:{{ certmanager_sha256_checksum }}
        dest: '{{ k3s_map.node.directory.bin }}/cmctl'
        owner: root
        group: root
        mode: '755'
      register: certmanager_result
      delay: 1
      retries: 3
      until: certmanager_result is not failed

    - name: Create symlink
      ansible.builtin.file:
        path: '{{ k3s_map.node.directory.bin }}/kubectl-cert_manager'
        src: '{{ k3s_map.node.directory.bin }}/cmctl'
        state: link

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ certmanager_vars.kubernetes.helm.repository.org }}'
        repo_url: '{{ certmanager_vars.kubernetes.helm.repository.url }}'
        force_update: true
      register: certmanager_result
      delay: 1
      retries: 3
      until: certmanager_result is not failed

    - name: Chart Setup
      run_once: true
      block:
        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            certmanager_postinstall: false

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: '{{ certmanager_map.helm.chart.reference }}'
            chart_version: '{{ certmanager_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ certmanager_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ certmanager_vars.kubernetes.namespace }}'
            timeout: '{{ certmanager_map.helm.timeout }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            create_namespace: true
            update_repo_cache: true
            wait: true
          register: certmanager_result
          delay: 1
          retries: 3
          until: certmanager_result is not failed

        - name: Create self-signed cluster issuer
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'cluster_issuer.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true
