---
- name: Restart cache service
  ansible.builtin.systemd_service:
    name: helm-cache.service
    state: restarted
    daemon_reload: true
    enabled: true

- name: Start cache service
  ansible.builtin.systemd_service:
    name: helm-cache.service
    state: started
    daemon_reload: true
    enabled: true
