---
- name: Set acme server fact
  ansible.builtin.set_fact:
    cloudflare_acme_server: "{{ '-staging' if cloudflare_vars.kubernetes.acme.server == 'staging' | default('') }}"
  run_once: true

- name: Set acme server url fact
  ansible.builtin.set_fact:
    cloudflare_acme_server_url: https://acme{{ cloudflare_acme_server }}-v02.api.letsencrypt.org/directory
  run_once: true

- name: Set cluster issuer fact
  ansible.builtin.set_fact:
    cloudflare_cluster_issuer: '{{ cloudflare_vars.kubernetes.tls.cluster_issuer.name }}{{ cloudflare_acme_server }}'
  run_once: true

- name: Set project chart fact
  ansible.builtin.set_fact:
    cloudflare_project_chart: '{{ cloudflare_vars.kubernetes.helm.repository.org }}/{{ cloudflare_vars.kubernetes.helm.repository.name }}'
  run_once: true

- name: Set project tag fact
  ansible.builtin.set_fact:
    cloudflare_project_tag: '{{ cloudflare_vars.kubernetes.helm.chart.name }}-helm-chart-{{ cloudflare_vars.kubernetes.helm.chart.version[1:] }}'
  run_once: true

- name: Set project url fact
  ansible.builtin.set_fact:
    cloudflare_project_url: https://github.com/{{ cloudflare_project_chart }}/releases/tag
  run_once: true

- name: Set project tag url fact
  ansible.builtin.set_fact:
    cloudflare_project_url_tag: '{{ cloudflare_project_url }}/{{ cloudflare_project_tag }}'
  run_once: true

- name: Set tls prefix fact
  ansible.builtin.set_fact:
    cloudflare_tls_key_prefix: '{{ cloudflare_vars.kubernetes.tls.key_prefix }}'
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    cloudflare_vars: '{{ cloudflare_vars }}'
  run_once: true
